Polish PreferSafeLoggableExceptions
palantir/gradle-baseline pull request #441
Opened 2018-10-24 15:39 UTC by iamdanfox

Follow-up to https://github.com/palantir/gradle-baseline/pull/440 after I tried it locally:

- adds a nice link
- turns it off in test code to minimize noise

2018-10-25 09:22 UTC, robert3005 requested changes

2018-10-25 09:22 UTC, robert3005 commented on baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptions.java
> +                .anyMatch(ancestor -> JUnitMatchers.hasJUnit4TestCases.matches((ClassTree) ancestor, state));
please make this handle junit5

2018-10-26 07:43 UTC, iamdanfox commented on baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/PreferSafeLoggableExceptions.java
> +                .anyMatch(ancestor -> JUnitMatchers.hasJUnit4TestCases.matches((ClassTree) ancestor, state));
done

2018-10-26 13:02 UTC, robert3005 approved these changes

2018-10-26 13:03 UTC, merged