[improvement] Disallow Multimap.keys() by default
palantir/gradle-baseline pull request #549
Opened 2019-02-24 14:10 UTC by mattsills

## Before this PR

## After this PR

2019-02-25 11:00 UTC, j-baker commented on baseline-error-prone/src/main/java/com/palantir/baseline/errorprone/MultimapKeys.java
> +            .withNameMatching(Pattern.compile("keys"));
given what this is, should probably be `.named("keys")` rather than invoking the regex version?

2019-02-25 11:33 UTC, iamdanfox commented on README.md
> +- `MultimapKeys`: `Multimap.keys()` is usually an error, where the author meant to use `Multimap.keySet()`.
Don't think it's really good enough to say "foo is usually an error", as that is true by definition for all the checks - this sentence needs to explain to people _why_ we consider this a foot gun!

2019-02-26 18:28 UTC, iamdanfox requested changes
@mattsills can you fix up the messaging here please? Would be great to get this into the next release

2019-03-05 23:12 UTC, cakofony commented
@mattsills Are you still working on this? I'd like to take advantage of it when it's ready :-)

2019-06-04 16:51 UTC, closed without merging